const MyResourcesConstants = {
    SET_LOADING : 'SET_MYRESOURCE_LOADING',
    SET_DATA : 'SET_DATA',
    ADD_RESOURCE : 'ADD_RESOURCE',
    EDIT_RESOURCE : 'EDIT_RESOURCE',
    DELETE_RESOURCE : 'DELETE_RESOURCE',
    SAVE_RESOURCE_FOR_LATER : 'SAVE_RESOURCE_FOR_LATER'
}

export default MyResourcesConstants;