const requestConstants = {
    SET_LOADING : 'SET_REQUEST_LOADING',
    SET_REQUEST : 'SET_RESOURCE',
    SET_REQUESTS : 'SET_REQUESTS',
    ADD_REQUEST : 'ADD_REQUEST',
    DELETE_REQUEST : 'DELETE_REQUEST',
    EDIT_REQUEST  : 'EDIT_REQUEST',
    SET_IS_EXISTS : 'SET_IS_EXISTS',
    SET_DATA : "SET_DATA"
 
}
export default requestConstants;