const requestConstants = {
    SET_LOADING : 'SET_REQUEST_LOADING',
    SET_REQUIREMENTS : 'SET_REQUIREMENTS',
    ADD_REQUIREMENTS : 'ADD_REQUIREMENTS',
    DELETE_REQUIREMENTS : 'DELETE_REQUIREMENTS',
    EDIT_REQUIREMENTS : 'EDIT_REQUIREMENTS',
}
export default requestConstants;